### ISSUE TITLE
Improve legibility

### ISSUE THREAD

**Issue by mollierobbert** [mollie/api-documentation#46]
The old docs (https://www.mollie.com/en/docs) are far more legible than the new ones.

The content column as well as the default font size are too small.

**Comment by adriaanmol** [comment]
What are you guys going to change then? Please also discuss with Giel.

@mattijsbliek doesn't need to be constituent with payment method pages because we are likely going to change that also another moment (iterating).

**Comment by mollierobbert** [comment]
We want to increase the font size and the width of the body. Additionally the sidebar is currently misaligned. These are your suggestions from our most recent discussion on the new docs styling, Adriaan.

CC @gielcobben

**Comment by vernondegoede** [comment]
- The body font size has been increased a few days ago by @Marinolinderhof (in #71).
- Regarding the width of the content area; the optimal line length for your body text is [considered to be 50-60 characters per line](https://baymard.com/blog/line-length-readability), including spaces. This is currently the case.
- Collapsed subnavigation bar now shows text instead of icons.

**Comment by mollierobbert** [comment]
What about the misalignment of the sidebar?
