### ISSUE TITLE
Mobile navigation is too vague

### ISSUE THREAD

**Issue by mollierobbert** [mollie/api-documentation#55]
The mobile navigation button that makes the endpoint list appear is awkwardly placed, and the two-arrow icon used is not a well-known symbol for a navigation.

**Comment by vernondegoede** [comment]
Just had a quick discussion on this with @gielcobben.

We don't agree on the awkward positioning of this icon. The position of this icon makes it easy to navigate between the different endpoints, especially on mobile devices. It's based on the Material Design floating action button, which is usually also positioned like this.

We do agree on the use of the symbol though. Do you have a suggestion for a better icon? A hamburger icon might not be sufficient, since this one is usually used for the main navigation. This icon basically just acts as a table of contents.

**Comment by mollierobbert** [comment]
Material-style action buttons are not meant for toggling menus. I would still consider this bad UX.

Perhaps Giel can incorporate this in his docs redesign?

I agree it has little priority though.
