### ISSUE TITLE
Test checkout only calls webwhook when the status is "paid"

### ISSUE THREAD

**Issue by druc** [mollie/api-documentation#641]
Hello, 

I ran into the same issue described here: #613  (webhook only gets called when the status is "paid")

https://www.loom.com/share/cb97c6fd084247b48193623839589197

I'm using v2 of the api and the latest mollie php client.

Example payment ID: `tr_xQrkR6s7rt`

Any help would be much appreciated

**Comment by MollieRick** [comment]
Hello @druc,

You haven't specified a method on your call. Therefor, the consumer is able to choose another method when the payment is, for example, canceled. The only webhook you got was because the payment was expired.

If you specify a method, and choose the payment to e.g. fail, that will trigger the webhook for the status `failed`.
