### ISSUE TITLE
Improve documentation of `locale` parameter

### ISSUE THREAD

**Issue by remcotolsma** [mollie/api-documentation#653]
https://github.com/mollie/api-documentation/blob/96fe926f881bc61eda9c22cbe52192ddd6a6b710/source/reference/v2/payments-api/create-payment.rst#L103-L117

We find it confusing that `nl` is not working but `nl_NL_formal` for example does work.

> You can provide any ISO 15897 locale, but our hosted payment pages currently only support the following languages:

- `gl_ES` not listed, but works.
- `en_CA` not listed, but works.
- `bl_AB` not listed, error `Unprocessable Entity - The locale is invalid`.
- `nl_NL_formal` not listed but works, Dutch payment page.
- `nl_NL_XXXX` not listed but works, Dutch payment page.
- `nl_NL2` not listed but works, Dutch payment page.
- `nl-NL` not listed but works, Dutch payment page.
- `nl_NL🐛` not listed but works, Dutch payment page.
- `nl NL` not listed, error `Unprocessable Entity - The locale is invalid`.
- `nl` not listed, error `Unprocessable Entity - The locale is invalid`.
- `uz_UZ` not listed, error `Unprocessable Entity - The locale is invalid`.
- `uz` not listed, error `Unprocessable Entity - The locale is invalid`.

It is unpredictable when an unsupported locale will result in a `Unprocessable Entity - The locale is invalid` error. Are `nl` and `uz_UZ` not ISO 15897 locales?

https://docs.mollie.com/reference/v2/payments-api/create-payment.

**Comment by mollierobbert** [comment]
Thanks for reporting this, Remco.

Our API currently only supports the `xx_XX` notation. We ignore anything after the fifth character, so that explains some of the behavior you are seeing.

According to ISO 15897 the locale `cs_CZ.UTF-8` is also valid, but we parse that as `cs_CZ` to keep things simple for ourselves.

It's not bulletproof though, since for example `yue_Hans_CN` is also a valid locale according to that ISO standard (simplified Cantonese, China). Since we don't support three-letter languages like `yue`, nor support script indicators like `Hans`, we would not be able to parse that locale.

I agree `nl` should also be supported.

As for `uz_UZ`, we rely on the ICU library to verify whether the locale string is considered valid. That library only knows these `uz` locales:

```
uz
uz_Arab
uz_Arab_AF
uz_Cyrl
uz_Cyrl_UZ
uz_Latn
uz_Latn_UZ
```

So, since our API currently does not accept `xx` notation nor `xx_Xxx_XX` notation, it seems we cannot offer support for any Uzbek locale value currently.

For now, I would recommend sticking to the 'simpler' locales listed in the Create payment endpoint documentation.

I'll update the docs to reflect the limitation.

@rosstuck CC. We should track this issue internally so we don't lose sight on it, especially given our continued international expansion.

**Comment by mollierobbert** [comment]
In 3216aa4 I clarified that we only support `xx_XX` format.

I'm closing the issue now, since it's no longer an API docs issue. Internally we'll track the actual improvement of expanding locale support.
