### ISSUE TITLE
double click to open payment

### ISSUE THREAD

**Issue by JatGitHub** [mollie/api-documentation#666]
Hi,

Whenever starting a new payment, I always get this, after clicking on any payment method:

![afbeelding](https://user-images.githubusercontent.com/9821114/93878420-56598980-fcda-11ea-84c5-999040a2a21a.png)

Not a real big issue, but it is annoying. 
Hope somebody can remove this.

Kind regards,
Jeroen

**Comment by willemstuursma** [comment]
Hi @JatGitHub. What browser are you using? Any extensions installed?

**Comment by JatGitHub** [comment]
Firefox, Edge gives the same result. Edge is clean, I never use it. Chrome likewise.

**Comment by mollierobbert** [comment]
Thanks for the report, Jeroen. This seems to only happen if you wait for too long to select the payment method. I think the timeout on the form is around 10-15 minutes.

@pabloroman We could improve the message, or perhaps drop CSRF protection altogether since the form on this page is probably not interesting for an attacker.

Since this is not related to our API documentation, I'll close the issue.
