### ISSUE TITLE
Clarify when payments do not have a checkout url.

### ISSUE THREAD

**Issue by wgevaert** [mollie/api-documentation#724]
Currently, the documentation of the [get_payment](https://docs.mollie.com/reference/v2/payments-api/get-payment) api states that `_links`->`checkout` is optional, with the remark `Recurring payments do not have a checkout URL`.

However, there are more situations when a payment does not have a checkout URL, for example an iDeal-payment that failed or a bank transfer payment that has been paid.

Can this be indicated here somehow?

**Comment by MollieRick** [comment]
Hi @wgevaert,

We think that it makes sense that a completed payment (when it is `paid`, `canceled`, `failed`, etc.) does not have a checkout url. The reason why we explicit mention that recurring payments does not have a checkout url is because that payment is not completed yet as mentioned.

Thanks for thinking with us, but I think this change is not necessary.
