### ISSUE TITLE
LIST organizations API reference page link missing

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#743]
The LIST page is referenced on the [GET page](https://docs.mollie.com/reference/v2/organizations-api/get-organization), but the link only appears in the nav when the LIST page is active - which is currently only reachable by pasting a direct url:

https://docs.mollie.com/reference/v2/organizations-api/list-organizations

<img width="208" alt="image" src="https://user-images.githubusercontent.com/7265703/112886305-08cb3880-90d2-11eb-9922-9558ea1513a6.png"> <img width="208" alt="image" src="https://user-images.githubusercontent.com/7265703/112886195-e2a59880-90d1-11eb-8847-de6b74b7c29a.png">

**Comment by mollierobbert** [comment]
Good catch. Because this endpoint is only available to partners, the page has been moved to the semi-hidden partner section (`/reference/reseller-api/v2/list-organizations`). But, because of issue #54, the old page with the old navigation is still showing on the old URL.

I'm merging this issue with #54.

**Comment by mollierobbert** [comment]
We solved the issue of stale files in #54, and I put a redirect in place with 978640a. So now the link you shared points to the new location.
