### ISSUE TITLE
Implement search functionality

### ISSUE THREAD

**Issue by vernondegoede** [mollie/api-documentation#82]
We currently don't use the search functionality which comes with Sphinx by default. We should either:

1) Use [Algolia DocSearch](https://community.algolia.com/docsearch/)
2) Keep the default Python OpenSearch functionality

I'd prefer to use Algolia DocSearch, since it comes with powerful autocompletion. This will allow developers to easily find the right resource.

**Comment by willemstuursma** [comment]
Looks like a data harvester - since it is free we are the product.

**Comment by sandervanhooft** [comment]
Algolia has [tiered pricing / free-for-open-source](https://www.algolia.com/pricing). Like other platforms such as Travis.

So I am not sure about the "data harvester" role. Also, as the docs are open source, I don't see the issue here. (They could be indexing github already - probably not).

My guess is you'd have less maintenance on Algolia than on OpenSearch. (Unless there's already OpenSearch knowledge inhouse.)

There's also ElasticSearch (loved it, not that hard to implement), but in my experience the clients are not as easy and stable as for what I've seen from Algolia.

**Comment by mattijsbliek** [comment]
They’re crawling publicly available pages, and are doing so for both major open source projects as well as large companies: https://community.algolia.com/docsearch/. I think their play is to get you familiar with Algolia, so that you will use their paid products over those of the competition.

The entire DocSearch project is open source, and I haven’t seen any behavior from Algolia that would make me mistrust them. I think it would be fine to implement.

**Comment by sandervanhooft** [comment]
Do check if Mollie qualifies for Algolia's open source plan limitations ([here](https://www.algolia.com/for-open-source)). Also, the number of monthly operations seem to be capped.

**Comment by sandervanhooft** [comment]
(Algolia is also heavily involved in the Laravel community by the way)

**Comment by mattijsbliek** [comment]
DocSearch is a community product and thus free of charge. The tiered pricing is only for their paid products.

@willemstuursma We can have compliance review their privacy policy to see what data they collect.

**Comment by vernondegoede** [comment]
@sandervanhooft I contacted them back in May already and they confirmed that docs.mollie.com qualifies for the open source plan.

**Comment by vernondegoede** [comment]
@georgemaine Do you have any idea where we could position the search? It will probably look similar to the search on https://reactjs.org.
