### ISSUE TITLE
Provide info on rate limits

### ISSUE THREAD

**Issue by jarroput** [mollie/api-documentation#845]
https://docs.mollie.com/overview/handling-errors

The documentation provides some information possible status codes.

For `429 - Too Many Requests` the docs mention: 
> Your request has hit a rate limit. Please wait for a bit and retry.

There is no information how to predictably act on this _or even better_ how to know you're going to exceed rate limits in advance by receiving that information in the headers of the API response.

**Comment by MollieRick** [comment]
Hi @jarroput,

Thanks for the suggestion, I will see if I can get more information on this topic to the docs.

**Comment by mollierobbert** [comment]
Having this information in the headers definitely makes sense. We are planning to improve our rate limit capabilities in the next year or so, improving consistency across the APIs. We will then likely implement a header-based approach indeed.

I will have to close this issue for now, since we are removing this GitHub repository in favor of the new Mollie API documentation stack.
